name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_bin:
    runs-on: [self-hosted, esp32]
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/cache@master
      id: tools
      with:
        path: |
          tools
          ~/.espressif
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install esp-idf
      if: steps.tools.outputs.cache-hit != 'true'
      run: |
        cd tools
        git clone --recursive https://github.com/espressif/esp-idf.git
    - name: test
      run: |
        bash tools/esp-idf/install.sh
        source tools/esp-idf/export.sh
        cd projects/code
        bash components/esp_lua_lib/tools/lua_flash.sh /dev/ttyUSB0 921600 0x300000 0x100000 1 1 0
        esptool.py -p /dev/ttyUSB0 -b 921600 read_flash 0x0 0x400000 udisk.bin
    - uses: actions/upload-artifact@v2
      with:
        name: bin
        path: projects/code/udisk.bin
    
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: gen image bin
      run: |
        . add_path.sh
        cd docs/img
        bash gen_bin.sh
        mv build img 
        ls img/

    - uses: actions/upload-artifact@v2
      with:
        name: img
        path: docs/img/img

  deploy:
    runs-on: ubuntu-latest
    needs: [build_bin, build_image]
    if: github.event_name == 'push'
    env:
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SERVER_OUTPUT_PATH: ${{ secrets.SERVER_OUTPUT_PATH }}
    steps:
    - name: Setup Private Key
      run: |
        mkdir -p ~/.ssh/
        echo "$SERVER_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts

    - uses: actions/download-artifact@v2
      with:
        path: output

    - name: push data to server
      if: success()
      run: |
        ls -R output
        scp -P $SERVER_PORT output/* $SERVER_USER@$SERVER_HOST:$SERVER_OUTPUT_PATH


