name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [self-hosted, esp32]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/cache@v2
      id: tools
      with:
        path: |
          tools
          ~/.espressif
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install esp-idf
      if: steps.tools.outputs.cache-hit != 'true'
      run: |
        cd tools
        git clone --recursive https://github.com/espressif/esp-idf.git
    - name: test
      run: |
        bash tools/esp-idf/install.sh
        source tools/esp-idf/export.sh
        cd projects/code
        idf.py build flash
    
  deploy_image:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SERVER_OUTPUT_PATH: ${{ secrets.SERVER_OUTPUT_PATH }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Private Key
      run: |
        mkdir -p ~/.ssh/
        echo "$SERVER_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts

    - name: gen image bin
      run: |
        . add_path.sh
        cd docs/img
        bash gen_bin.sh
        ls build/
        scp -P $SERVER_PORT build/* $SERVER_USER@$SERVER_HOST:$SERVER_OUTPUT_PATH/img
