# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  SERVER_KEY: ${{ secrets.SERVER_KEY }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_OUTPUT_PATH: ${{ secrets.SERVER_OUTPUT_PATH }}

env:
  SERVER_KEY: ${{ secrets.SERVER_KEY }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_OUTPUT_PATH: ${{ secrets.SERVER_OUTPUT_PATH }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: test
      run: |
        echo "hello"
    
  deploy_image:
    if: github.event == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Private Key
      run: |
        mkdir -p ~/.ssh/
        echo "$SERVER_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts

    - name: gen image bin
      run: |
        . add_path.sh
        cd docs/img
        bash gen_bin.sh

    - name: push image bin
      if: ${{ success() }}
      run: |
        ls docs/img/build/
        scp -P $SERVER_PORT build/* $SERVER_USER@$SERVER_HOST:$SERVER_OUTPUT_PATH/img
